// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUn5hqDIhjSz1Sp_pgjWzDW4PGKrF-iaY',
    appId: '1:1026966721942:web:436ce040ca96d11443f9b7',
    messagingSenderId: '1026966721942',
    projectId: 'admob-app-id-4414975077',
    authDomain: 'admob-app-id-4414975077.firebaseapp.com',
    databaseURL: 'https://admob-app-id-4414975077.firebaseio.com',
    storageBucket: 'admob-app-id-4414975077.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmhyblABUjcRRsSHag2-WDDi1Gd3XibdA',
    appId: '1:1026966721942:android:2eab0f47afb44da243f9b7',
    messagingSenderId: '1026966721942',
    projectId: 'admob-app-id-4414975077',
    databaseURL: 'https://admob-app-id-4414975077.firebaseio.com',
    storageBucket: 'admob-app-id-4414975077.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM_mIzbZqiQuZOjvLfECe8musDqEYFY-8',
    appId: '1:1026966721942:ios:ee999a22d4324a2443f9b7',
    messagingSenderId: '1026966721942',
    projectId: 'admob-app-id-4414975077',
    databaseURL: 'https://admob-app-id-4414975077.firebaseio.com',
    storageBucket: 'admob-app-id-4414975077.appspot.com',
    androidClientId: '1026966721942-op0tdn279nevng5t4r23ikknm72ikmr5.apps.googleusercontent.com',
    iosClientId: '1026966721942-ksh6rd51n1lhqqsdfcatgr7q4ohbvedu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flightBooking',
  );
}
